CREATE OPAQUE TOPIC _schemas PROFILE two_wk_retain;
CREATE OPAQUE TOPIC CONFIG PROFILE two_wk_retain;
CREATE OPAQUE TOPIC OFFSET PROFILE two_wk_retain;
CREATE OPAQUE TOPIC STATUS PROFILE two_wk_retain;
